1. 뉴스 기반 조합 (6개)
- news_3class_all

- news_3class_score95

- news_3class_score90

- news_2class_all

- news_2class_score95

- news_2class_score90

2. 댓글 기반 조합
- comment_all

- comment_score90

- comment_all_count

- comment_score90_count

3. 뉴스 + 댓글 조합 (3class)
- news_3class_all + comment_all

- news_3class_all + comment_score90

- news_3class_all + comment_all_count

- news_3class_all + comment_score90_count

- news_3class_score95 + comment_all

- news_3class_score95 + comment_score90

- news_3class_score95 + comment_all_count

- news_3class_score95 + comment_score90_count

- news_3class_score90 + comment_all

- news_3class_score90 + comment_score90

- news_3class_score90 + comment_all_count

- news_3class_score90 + comment_score90_count

4. 뉴스 + 댓글 조합 (2class)
- news_2class_all + comment_all

- news_2class_all + comment_score90

- news_2class_all + comment_all_count

- news_2class_all + comment_score90_count

- news_2class_score95 + comment_all

- news_2class_score95 + comment_score90

- news_2class_score95 + comment_all_count

- news_2class_score95 + comment_score90_count

In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
def eda_basic_info(df, df_name="DataFrame"):
    print(f"\n===== {df_name} =====")
    print("Head (5 rows):")
    display(df.head())
    
    print("\nInfo:")
    print(df.info())
    
    print("\nDescribe (numeric):")
    display(df.describe())
    
    print("\nNull counts:")
    print(df.isnull().sum())
    
    print("="*40)

# 1. 전체 뉴스 감정 분석(긍정 부정 중립)

In [5]:
# 전체 뉴스 감정 분석(긍정 부정 중립)
df_fx = pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\data\df_investing2.csv")

df_sentiment = pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\naver_finance_news_sentiment_score.csv")

df_fx["date"] = pd.to_datetime(df_fx["date"]).dt.date
df_sentiment["date"] = pd.to_datetime(df_sentiment["date"]).dt.date

# 병합 
df= pd.merge(df_fx, df_sentiment[["date", "sentiment score"]], on="date", how="left")

In [6]:
eda_basic_info(df, "df") # 전체 뉴스 감정 분석(긍정 부정 중립)- sentiment score 결측치 수 314개

===== df =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.000000
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.000000
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.000000
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.666667
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.000000

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1186 non-null   object
 1   USD_KRW 종가       1186 non-null   float64
 2   USD_KRW 시가       1186 non-null   float64
 3   KOSPI 종가         1186 non-null   float64
 4   KOSPI 거래량        1186 non-null   float64
 5   KOSDAQ 종가        1186 non-null   float64
 6   KOSDAQ 거래량       1186 non-null   float64
 7   WTI Price        1186 non-null   float64
 8   XAU Price        1186 non-null   float64
 9   DJI 종가           1186 non-null   float64
 10  DJI 거래량          1186 non-null   float64
 11  SP500 종가         1186 non-null   float64
 12  M1               1186 non-null   float64
 13  M2               1186 non-null   float64
 14  한국 정책금리          1186 non-null   float64
 15  미국 정책금리          1186 non-null   float64
 16  CPI              1186 non-null   float64
 17  PPI              1186 non-null   float64
 18  경상수지             1186 non-null   float64
 19  sentiment score  872 non-null    float64
dtypes: float64(19), object(1)
memory usage: 185.4+ KB
None

Describe (numeric):

,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
count,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,872.000000
mean,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,-0.037137
std,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.883794
min,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.000000
25%,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,-1.000000
50%,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,0.000000
75%,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,1.000000
max,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000

Null counts:
date                 0
USD_KRW 종가           0
USD_KRW 시가           0
KOSPI 종가             0
KOSPI 거래량            0
KOSDAQ 종가            0
KOSDAQ 거래량           0
WTI Price            0
XAU Price            0
DJI 종가               0
DJI 거래량              0
SP500 종가             0
M1                   0
M2                   0
한국 정책금리              0
미국 정책금리              0
CPI                  0
PPI                  0
경상수지                 0
sentiment score    314
dtype: int64
========================================

In [9]:
# 결측치 0으로 채움
df["sentiment score"] = df["sentiment score"].fillna(0)

# scaler 객체 생성
scaler = StandardScaler()

# 'Z-score 정규화 
df['sentiment score'] = scaler.fit_transform(df[['sentiment score']])

In [10]:
eda_basic_info(df, "df")

===== df =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.283978
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.283978
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.283978
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.843971
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.036043

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1186 non-null   object
 1   USD_KRW 종가       1186 non-null   float64
 2   USD_KRW 시가       1186 non-null   float64
 3   KOSPI 종가         1186 non-null   float64
 4   KOSPI 거래량        1186 non-null   float64
 5   KOSDAQ 종가        1186 non-null   float64
 6   KOSDAQ 거래량       1186 non-null   float64
 7   WTI Price        1186 non-null   float64
 8   XAU Price        1186 non-null   float64
 9   DJI 종가           1186 non-null   float64
 10  DJI 거래량          1186 non-null   float64
 11  SP500 종가         1186 non-null   float64
 12  M1               1186 non-null   float64
 13  M2               1186 non-null   float64
 14  한국 정책금리          1186 non-null   float64
 15  미국 정책금리          1186 non-null   float64
 16  CPI              1186 non-null   float64
 17  PPI              1186 non-null   float64
 18  경상수지             1186 non-null   float64
 19  sentiment score  1186 non-null   float64
dtypes: float64(19), object(1)
memory usage: 185.4+ KB
None

Describe (numeric):

,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
count,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,1.186000e+03
mean,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,1.347994e-17
std,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,1.000422e+00
min,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.283978e+00
25%,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,-1.283978e+00
50%,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,3.604271e-02
75%,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,1.356063e+00
max,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.356063e+00

Null counts:
date               0
USD_KRW 종가         0
USD_KRW 시가         0
KOSPI 종가           0
KOSPI 거래량          0
KOSDAQ 종가          0
KOSDAQ 거래량         0
WTI Price          0
XAU Price          0
DJI 종가             0
DJI 거래량            0
SP500 종가           0
M1                 0
M2                 0
한국 정책금리            0
미국 정책금리            0
CPI                0
PPI                0
경상수지               0
sentiment score    0
dtype: int64
========================================

In [12]:
df.rename(columns={"sentiment score": "news_3class_score"}, inplace=True)
df.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,news_3class_score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.283978
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.283978
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.283978
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.843971
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.036043

In [13]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\news_3class_all.csv"
df.to_csv(output_path, index=False)

# 2. 전체 뉴스 감정 분석(긍정 부정)

In [20]:
# 전체 뉴스 감정 분석(긍정 부정)
df_fx = pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\data\df_investing2.csv")

df_binary =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\naver_finance_news_binary_sentiment_score.csv")

df_binary['date'] = pd.to_datetime(df_binary['date'].astype(int).astype(str), format="%Y%m%d")

In [22]:
df_fx["date"] = pd.to_datetime(df_fx["date"])

In [23]:
# 병합 
df2= pd.merge(df_fx, df_binary[["date", "sentiment score"]], on="date", how="left")

In [24]:
eda_basic_info(df2, "df2") # 긍부정 결측치 sentiment score  314

===== df2 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.000000
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.000000
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.000000
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.333333
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.000000

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1186 non-null   datetime64[ns]
 1   USD_KRW 종가       1186 non-null   float64
 2   USD_KRW 시가       1186 non-null   float64
 3   KOSPI 종가         1186 non-null   float64
 4   KOSPI 거래량        1186 non-null   float64
 5   KOSDAQ 종가        1186 non-null   float64
 6   KOSDAQ 거래량       1186 non-null   float64
 7   WTI Price        1186 non-null   float64
 8   XAU Price        1186 non-null   float64
 9   DJI 종가           1186 non-null   float64
 10  DJI 거래량          1186 non-null   float64
 11  SP500 종가         1186 non-null   float64
 12  M1               1186 non-null   float64
 13  M2               1186 non-null   float64
 14  한국 정책금리          1186 non-null   float64
 15  미국 정책금리          1186 non-null   float64
 16  CPI              1186 non-null   float64
 17  PPI              1186 non-null   float64
 18  경상수지             1186 non-null   float64
 19  sentiment score  872 non-null    float64
dtypes: datetime64[ns](1), float64(19)
memory usage: 185.4 KB
None

Describe (numeric):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
count,1186,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,872.000000
mean,2022-06-25 11:34:30.151770624,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,-0.131957
min,2020-01-02 00:00:00,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.000000
25%,2021-03-29 06:00:00,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,-1.000000
50%,2022-06-25 12:00:00,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,0.000000
75%,2023-09-18 18:00:00,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,1.000000
max,2024-12-30 00:00:00,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000
std,NaN,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.890156

Null counts:
date                 0
USD_KRW 종가           0
USD_KRW 시가           0
KOSPI 종가             0
KOSPI 거래량            0
KOSDAQ 종가            0
KOSDAQ 거래량           0
WTI Price            0
XAU Price            0
DJI 종가               0
DJI 거래량              0
SP500 종가             0
M1                   0
M2                   0
한국 정책금리              0
미국 정책금리              0
CPI                  0
PPI                  0
경상수지                 0
sentiment score    314
dtype: int64
========================================

In [26]:
df2["sentiment score"] = df2["sentiment score"].fillna(0)

In [27]:
scaler = StandardScaler()
df2['sentiment score'] = scaler.fit_transform(df2[['sentiment score']])

In [28]:
df2.rename(columns={"sentiment score": "news_2class_score"}, inplace=True)
df2.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,news_2class_score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.180277
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.180277
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.180277
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.308882
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.126815

In [29]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\news_2class_all.csv"
df2.to_csv(output_path, index=False)

# 3. 전체 뉴스 감정 분석(긍정 부정 중립) score > 0.95

In [31]:
df_filterd =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\naver_finance_news_sentiment_score_filtered.csv")

In [32]:
df_filterd["date"] = pd.to_datetime(df_filterd["date"]).dt.date

In [33]:
df_fx["date"] = pd.to_datetime(df_fx["date"]).dt.date

In [34]:
df3= pd.merge(df_fx, df_filterd[["date", "sentiment score"]], on="date", how="left")

In [35]:
eda_basic_info(df3, "df3") # 결측치 sentiment score  368개

===== df3 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1186 non-null   object
 1   USD_KRW 종가       1186 non-null   float64
 2   USD_KRW 시가       1186 non-null   float64
 3   KOSPI 종가         1186 non-null   float64
 4   KOSPI 거래량        1186 non-null   float64
 5   KOSDAQ 종가        1186 non-null   float64
 6   KOSDAQ 거래량       1186 non-null   float64
 7   WTI Price        1186 non-null   float64
 8   XAU Price        1186 non-null   float64
 9   DJI 종가           1186 non-null   float64
 10  DJI 거래량          1186 non-null   float64
 11  SP500 종가         1186 non-null   float64
 12  M1               1186 non-null   float64
 13  M2               1186 non-null   float64
 14  한국 정책금리          1186 non-null   float64
 15  미국 정책금리          1186 non-null   float64
 16  CPI              1186 non-null   float64
 17  PPI              1186 non-null   float64
 18  경상수지             1186 non-null   float64
 19  sentiment score  818 non-null    float64
dtypes: float64(19), object(1)
memory usage: 185.4+ KB
None

Describe (numeric):

,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
count,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,818.000000
mean,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,-0.023227
std,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.927613
min,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.000000
25%,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,-1.000000
50%,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,0.000000
75%,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,1.000000
max,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000

Null counts:
date                 0
USD_KRW 종가           0
USD_KRW 시가           0
KOSPI 종가             0
KOSPI 거래량            0
KOSDAQ 종가            0
KOSDAQ 거래량           0
WTI Price            0
XAU Price            0
DJI 종가               0
DJI 거래량              0
SP500 종가             0
M1                   0
M2                   0
한국 정책금리              0
미국 정책금리              0
CPI                  0
PPI                  0
경상수지                 0
sentiment score    368
dtype: int64
========================================

In [36]:
df3["sentiment score"] = df3["sentiment score"].fillna(0)

In [37]:
scaler = StandardScaler()
df3['sentiment score'] = scaler.fit_transform(df3[['sentiment score']])

In [39]:
df3.rename(columns={"sentiment score": "news_3class_95_score"}, inplace=True)
df3.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,news_3class_95_score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.277934
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.277934
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.277934
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.277934
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.020806

In [40]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\news_3class_95_score.csv"
df3.to_csv(output_path, index=False)

# 4. 전체 뉴스 감정 분석(긍정 부정 중립) score > 0.9

In [41]:
df_filterd2 =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\naver_finance_news_sentiment_score_filtered_0.9.csv")
df_filterd2["date"] = pd.to_datetime(df_filterd2["date"]).dt.date
df_fx["date"] = pd.to_datetime(df_fx["date"]).dt.date

df4= pd.merge(df_fx, df_filterd2[["date", "sentiment score"]], on="date", how="left")

In [43]:
eda_basic_info(df4, "df4") # 결측치 sentiment score  348개

===== df4 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1186 non-null   object
 1   USD_KRW 종가       1186 non-null   float64
 2   USD_KRW 시가       1186 non-null   float64
 3   KOSPI 종가         1186 non-null   float64
 4   KOSPI 거래량        1186 non-null   float64
 5   KOSDAQ 종가        1186 non-null   float64
 6   KOSDAQ 거래량       1186 non-null   float64
 7   WTI Price        1186 non-null   float64
 8   XAU Price        1186 non-null   float64
 9   DJI 종가           1186 non-null   float64
 10  DJI 거래량          1186 non-null   float64
 11  SP500 종가         1186 non-null   float64
 12  M1               1186 non-null   float64
 13  M2               1186 non-null   float64
 14  한국 정책금리          1186 non-null   float64
 15  미국 정책금리          1186 non-null   float64
 16  CPI              1186 non-null   float64
 17  PPI              1186 non-null   float64
 18  경상수지             1186 non-null   float64
 19  sentiment score  838 non-null    float64
dtypes: float64(19), object(1)
memory usage: 185.4+ KB
None

Describe (numeric):

,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
count,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,838.000000
mean,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,-0.035481
std,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.918217
min,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.000000
25%,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,-1.000000
50%,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,0.000000
75%,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,1.000000
max,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000

Null counts:
date                 0
USD_KRW 종가           0
USD_KRW 시가           0
KOSPI 종가             0
KOSPI 거래량            0
KOSDAQ 종가            0
KOSDAQ 거래량           0
WTI Price            0
XAU Price            0
DJI 종가               0
DJI 거래량              0
SP500 종가             0
M1                   0
M2                   0
한국 정책금리              0
미국 정책금리              0
CPI                  0
PPI                  0
경상수지                 0
sentiment score    348
dtype: int64
========================================

In [44]:
df4["sentiment score"] = df4["sentiment score"].fillna(0)
scaler = StandardScaler()
df4['sentiment score'] = scaler.fit_transform(df4[['sentiment score']])
df4.rename(columns={"sentiment score": "news_3class_90_score"}, inplace=True)
df4.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,news_3class_90_score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.263608
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.263608
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.263608
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.263608
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.032494

In [46]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\news_3class_90_score.csv"
df4.to_csv(output_path, index=False)

# 5. 전체 뉴스 감정 분석(긍정 부정) score > 0.95

In [56]:
df_filterd3 =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\naver_finance_news_binary_sentiment_score_filtered.csv")
df_filterd3["date"] = pd.to_datetime(df_filterd3["date"]).dt.date
df_fx["date"] = pd.to_datetime(df_fx["date"]).dt.date

In [57]:
df5= pd.merge(df_fx, df_filterd3[["date", "sentiment score"]], on="date", how="left")

In [58]:
eda_basic_info(df5, "df5") # 결측치 sentiment score  913개

===== df5 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,NaN
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,NaN
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,NaN
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,NaN
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,NaN

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1186 non-null   object
 1   USD_KRW 종가       1186 non-null   float64
 2   USD_KRW 시가       1186 non-null   float64
 3   KOSPI 종가         1186 non-null   float64
 4   KOSPI 거래량        1186 non-null   float64
 5   KOSDAQ 종가        1186 non-null   float64
 6   KOSDAQ 거래량       1186 non-null   float64
 7   WTI Price        1186 non-null   float64
 8   XAU Price        1186 non-null   float64
 9   DJI 종가           1186 non-null   float64
 10  DJI 거래량          1186 non-null   float64
 11  SP500 종가         1186 non-null   float64
 12  M1               1186 non-null   float64
 13  M2               1186 non-null   float64
 14  한국 정책금리          1186 non-null   float64
 15  미국 정책금리          1186 non-null   float64
 16  CPI              1186 non-null   float64
 17  PPI              1186 non-null   float64
 18  경상수지             1186 non-null   float64
 19  sentiment score  273 non-null    float64
dtypes: float64(19), object(1)
memory usage: 185.4+ KB
None

Describe (numeric):

,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
count,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,273.000000
mean,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,0.420024
std,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.903546
min,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.000000
25%,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,-1.000000
50%,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,1.000000
75%,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,1.000000
max,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000

Null counts:
date                 0
USD_KRW 종가           0
USD_KRW 시가           0
KOSPI 종가             0
KOSPI 거래량            0
KOSDAQ 종가            0
KOSDAQ 거래량           0
WTI Price            0
XAU Price            0
DJI 종가               0
DJI 거래량              0
SP500 종가             0
M1                   0
M2                   0
한국 정책금리              0
미국 정책금리              0
CPI                  0
PPI                  0
경상수지                 0
sentiment score    913
dtype: int64
========================================

In [59]:
df5["sentiment score"] = df5["sentiment score"].fillna(0)
scaler = StandardScaler()
df5['sentiment score'] = scaler.fit_transform(df5[['sentiment score']])
df5.rename(columns={"sentiment score": "news_2class_95_score"}, inplace=True)
df5.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,news_2class_95_score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.206838
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.206838
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.206838
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.206838
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.206838

In [60]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\news_2class_95_score.csv"
df5.to_csv(output_path, index=False)

# 6. 전체 뉴스 감정 분석(긍정 부정) score > 0.90

In [52]:
df_filterd4 =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\naver_finance_news_sentiment_score_filtered_0.9.csv")
df_filterd4["date"] = pd.to_datetime(df_filterd4["date"]).dt.date
df_fx["date"] = pd.to_datetime(df_fx["date"]).dt.date

In [53]:
df6= pd.merge(df_fx, df_filterd4[["date", "sentiment score"]], on="date", how="left")

In [54]:
eda_basic_info(df6, "df6") # 결측치 sentiment score  483개

===== df6 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1186 non-null   object
 1   USD_KRW 종가       1186 non-null   float64
 2   USD_KRW 시가       1186 non-null   float64
 3   KOSPI 종가         1186 non-null   float64
 4   KOSPI 거래량        1186 non-null   float64
 5   KOSDAQ 종가        1186 non-null   float64
 6   KOSDAQ 거래량       1186 non-null   float64
 7   WTI Price        1186 non-null   float64
 8   XAU Price        1186 non-null   float64
 9   DJI 종가           1186 non-null   float64
 10  DJI 거래량          1186 non-null   float64
 11  SP500 종가         1186 non-null   float64
 12  M1               1186 non-null   float64
 13  M2               1186 non-null   float64
 14  한국 정책금리          1186 non-null   float64
 15  미국 정책금리          1186 non-null   float64
 16  CPI              1186 non-null   float64
 17  PPI              1186 non-null   float64
 18  경상수지             1186 non-null   float64
 19  sentiment score  703 non-null    float64
dtypes: float64(19), object(1)
memory usage: 185.4+ KB
None

Describe (numeric):

,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,sentiment score
count,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,703.000000
mean,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,-0.164533
std,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.947308
min,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.000000
25%,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,-1.000000
50%,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,-1.000000
75%,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,1.000000
max,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000

Null counts:
date                 0
USD_KRW 종가           0
USD_KRW 시가           0
KOSPI 종가             0
KOSPI 거래량            0
KOSDAQ 종가            0
KOSDAQ 거래량           0
WTI Price            0
XAU Price            0
DJI 종가               0
DJI 거래량              0
SP500 종가             0
M1                   0
M2                   0
한국 정책금리              0
미국 정책금리              0
CPI                  0
PPI                  0
경상수지                 0
sentiment score    483
dtype: int64
========================================

In [61]:
df6["sentiment score"] = df6["sentiment score"].fillna(0)
scaler = StandardScaler()
df6['sentiment score'] = scaler.fit_transform(df6[['sentiment score']])
df6.rename(columns={"sentiment score": "news_2class_90_score"}, inplace=True)
df6.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,news_2class_90_score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.230727
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.230727
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.230727
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.230727
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.230727

In [62]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\news_2class_90_score.csv"
df6.to_csv(output_path, index=False)

# 7. 댓글 감정 분석(긍정 부정)

In [63]:
df_comment =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\investing_comment_sentiment_score.csv")

In [64]:
df_comment['date'] = pd.to_datetime(df_comment['date'], format="%Y-%m-%d", errors="coerce")
df_fx["date"] = pd.to_datetime(df_fx["date"])

In [65]:
df7= pd.merge(df_fx, df_comment[["date", "score"]], on="date", how="left") #, "total_comments"

In [66]:
eda_basic_info(df7, "df7") # 결측치 sentiment score  0개

===== df7 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.188119
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.212048
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.395904
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.285333
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.333333

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1186 non-null   datetime64[ns]
 1   USD_KRW 종가  1186 non-null   float64
 2   USD_KRW 시가  1186 non-null   float64
 3   KOSPI 종가    1186 non-null   float64
 4   KOSPI 거래량   1186 non-null   float64
 5   KOSDAQ 종가   1186 non-null   float64
 6   KOSDAQ 거래량  1186 non-null   float64
 7   WTI Price   1186 non-null   float64
 8   XAU Price   1186 non-null   float64
 9   DJI 종가      1186 non-null   float64
 10  DJI 거래량     1186 non-null   float64
 11  SP500 종가    1186 non-null   float64
 12  M1          1186 non-null   float64
 13  M2          1186 non-null   float64
 14  한국 정책금리     1186 non-null   float64
 15  미국 정책금리     1186 non-null   float64
 16  CPI         1186 non-null   float64
 17  PPI         1186 non-null   float64
 18  경상수지        1186 non-null   float64
 19  score       1186 non-null   float64
dtypes: datetime64[ns](1), float64(19)
memory usage: 185.4 KB
None

Describe (numeric):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,score
count,1186,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,1186.000000
mean,2022-06-25 11:34:30.151770624,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,0.379844
min,2020-01-02 00:00:00,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-0.250000
25%,2021-03-29 06:00:00,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,0.305501
50%,2022-06-25 12:00:00,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,0.375956
75%,2023-09-18 18:00:00,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,0.451808
max,2024-12-30 00:00:00,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000
std,NaN,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.130490

Null counts:
date          0
USD_KRW 종가    0
USD_KRW 시가    0
KOSPI 종가      0
KOSPI 거래량     0
KOSDAQ 종가     0
KOSDAQ 거래량    0
WTI Price     0
XAU Price     0
DJI 종가        0
DJI 거래량       0
SP500 종가      0
M1            0
M2            0
한국 정책금리       0
미국 정책금리       0
CPI           0
PPI           0
경상수지          0
score         0
dtype: int64
========================================

In [68]:
df7["score"] = df7["score"].fillna(0) #어차피 결측치 없음
scaler = StandardScaler()
df7['score'] = scaler.fit_transform(df7[['score']])

In [69]:
df7.rename(columns={"score": "comment_score"}, inplace=True)
df7.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,comment_score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.469888
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.286430
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.123131
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.724579
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.356580

In [70]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\comment_score.csv"
df7.to_csv(output_path, index=False)

# 8. 댓글 감정 분석(긍정 부정) Score > 0.9

In [77]:
df_filterd7 =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\investing_comment_sentiment_score_0.9.csv")

In [78]:
df_filterd7["date"] = pd.to_datetime(df_filterd7["date"]).dt.date
df_fx["date"] = pd.to_datetime(df_fx["date"]).dt.date

In [79]:
df8= pd.merge(df_fx, df_filterd7[["date", "score"]], on="date", how="left")

In [80]:
eda_basic_info(df8, "df8") # 결측치 sentiment score  11개

===== df8 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,score
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.176471
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.132075
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.473684
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.304348
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.142857

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1186 non-null   object
 1   USD_KRW 종가  1186 non-null   float64
 2   USD_KRW 시가  1186 non-null   float64
 3   KOSPI 종가    1186 non-null   float64
 4   KOSPI 거래량   1186 non-null   float64
 5   KOSDAQ 종가   1186 non-null   float64
 6   KOSDAQ 거래량  1186 non-null   float64
 7   WTI Price   1186 non-null   float64
 8   XAU Price   1186 non-null   float64
 9   DJI 종가      1186 non-null   float64
 10  DJI 거래량     1186 non-null   float64
 11  SP500 종가    1186 non-null   float64
 12  M1          1186 non-null   float64
 13  M2          1186 non-null   float64
 14  한국 정책금리     1186 non-null   float64
 15  미국 정책금리     1186 non-null   float64
 16  CPI         1186 non-null   float64
 17  PPI         1186 non-null   float64
 18  경상수지        1186 non-null   float64
 19  score       1175 non-null   float64
dtypes: float64(19), object(1)
memory usage: 185.4+ KB
None

Describe (numeric):

,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,score
count,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,1175.000000
mean,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,0.440715
std,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.390111
min,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.000000
25%,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,0.200000
50%,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,0.468354
75%,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,0.714286
max,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000

Null counts:
date           0
USD_KRW 종가     0
USD_KRW 시가     0
KOSPI 종가       0
KOSPI 거래량      0
KOSDAQ 종가      0
KOSDAQ 거래량     0
WTI Price      0
XAU Price      0
DJI 종가         0
DJI 거래량        0
SP500 종가       0
M1             0
M2             0
한국 정책금리        0
미국 정책금리        0
CPI            0
PPI            0
경상수지           0
score         11
dtype: int64
========================================

In [81]:
df8["score"] = df8["score"].fillna(0)
scaler = StandardScaler()
df8['score'] = scaler.fit_transform(df8[['score']])
df8.rename(columns={"score": "comment_score_0.9"}, inplace=True)
df8.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,comment_score_0.9
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.666344
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.456628
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.094914
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.338810
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.752439

In [82]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\comment_score_0.9.csv"
df8.to_csv(output_path, index=False)

# 9. 댓글 감정 분석(긍정 부정) + 댓글 갯수

In [83]:
df_comment =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\investing_comment_sentiment_score.csv")

In [84]:
df_comment['date'] = pd.to_datetime(df_comment['date'], format="%Y-%m-%d", errors="coerce")
df_fx["date"] = pd.to_datetime(df_fx["date"])

In [85]:
df9= pd.merge(df_fx, df_comment[["date", "score", "total_comments"]], on="date", how="left")

In [86]:
eda_basic_info(df9, "df9") # 결측치 sentiment score  0개

===== df9 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,...,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,score,total_comments
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,...,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.188119,202
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,...,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.212048,830
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,...,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.395904,586
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,...,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.285333,375
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,...,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.333333,252

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            1186 non-null   datetime64[ns]
 1   USD_KRW 종가      1186 non-null   float64
 2   USD_KRW 시가      1186 non-null   float64
 3   KOSPI 종가        1186 non-null   float64
 4   KOSPI 거래량       1186 non-null   float64
 5   KOSDAQ 종가       1186 non-null   float64
 6   KOSDAQ 거래량      1186 non-null   float64
 7   WTI Price       1186 non-null   float64
 8   XAU Price       1186 non-null   float64
 9   DJI 종가          1186 non-null   float64
 10  DJI 거래량         1186 non-null   float64
 11  SP500 종가        1186 non-null   float64
 12  M1              1186 non-null   float64
 13  M2              1186 non-null   float64
 14  한국 정책금리         1186 non-null   float64
 15  미국 정책금리         1186 non-null   float64
 16  CPI             1186 non-null   float64
 17  PPI             1186 non-null   float64
 18  경상수지            1186 non-null   float64
 19  score           1186 non-null   float64
 20  total_comments  1186 non-null   int64
dtypes: datetime64[ns](1), float64(19), int64(1)
memory usage: 194.7 KB
None

Describe (numeric):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,...,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,score,total_comments
count,1186,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,...,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,1186.000000,1186.000000
mean,2022-06-25 11:34:30.151770624,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,...,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,0.379844,208.709949
min,2020-01-02 00:00:00,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,...,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-0.250000,4.000000
25%,2021-03-29 06:00:00,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,...,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,0.305501,75.000000
50%,2022-06-25 12:00:00,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,...,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,0.375956,150.000000
75%,2023-09-18 18:00:00,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,...,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,0.451808,267.750000
max,2024-12-30 00:00:00,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,...,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000,1451.000000
std,NaN,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,...,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.130490,199.323599

Null counts:
date              0
USD_KRW 종가        0
USD_KRW 시가        0
KOSPI 종가          0
KOSPI 거래량         0
KOSDAQ 종가         0
KOSDAQ 거래량        0
WTI Price         0
XAU Price         0
DJI 종가            0
DJI 거래량           0
SP500 종가          0
M1                0
M2                0
한국 정책금리           0
미국 정책금리           0
CPI               0
PPI               0
경상수지              0
score             0
total_comments    0
dtype: int64
========================================

In [87]:
df9["score"] = df9["score"].fillna(0) #어차피 결측치 없음
scaler = StandardScaler()
df9['score'] = scaler.fit_transform(df9[['score']])
df9.rename(columns={"score": "comment_score"}, inplace=True)
df9.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,...,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,comment_score,total_comments
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,...,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.469888,202
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,...,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.286430,830
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,...,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.123131,586
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,...,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.724579,375
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,...,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.356580,252

In [88]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\comment_score_with_count.csv"
df9.to_csv(output_path, index=False)

# 10. 댓글 감정 분석(긍정 부정) Score > 0.9 + 댓글 갯수

In [89]:
df_filterd8 =  pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\crawler\data\investing_comment_sentiment_score_0.9.csv")

In [90]:
df_filterd8["date"] = pd.to_datetime(df_filterd8["date"]).dt.date
df_fx["date"] = pd.to_datetime(df_fx["date"]).dt.date

In [93]:
df10= pd.merge(df_fx, df_filterd8[["date", "score", "total_comments"]], on="date", how="left")

In [94]:
eda_basic_info(df10, "df10") # 결측치 sentiment score  11개 total_comments    11

===== df10 =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,...,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,score,total_comments
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,...,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.176471,17.0
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,...,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.132075,53.0
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,...,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.473684,38.0
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,...,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.304348,23.0
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,...,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.142857,14.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            1186 non-null   object
 1   USD_KRW 종가      1186 non-null   float64
 2   USD_KRW 시가      1186 non-null   float64
 3   KOSPI 종가        1186 non-null   float64
 4   KOSPI 거래량       1186 non-null   float64
 5   KOSDAQ 종가       1186 non-null   float64
 6   KOSDAQ 거래량      1186 non-null   float64
 7   WTI Price       1186 non-null   float64
 8   XAU Price       1186 non-null   float64
 9   DJI 종가          1186 non-null   float64
 10  DJI 거래량         1186 non-null   float64
 11  SP500 종가        1186 non-null   float64
 12  M1              1186 non-null   float64
 13  M2              1186 non-null   float64
 14  한국 정책금리         1186 non-null   float64
 15  미국 정책금리         1186 non-null   float64
 16  CPI             1186 non-null   float64
 17  PPI             1186 non-null   float64
 18  경상수지            1186 non-null   float64
 19  score           1175 non-null   float64
 20  total_comments  1175 non-null   float64
dtypes: float64(20), object(1)
memory usage: 194.7+ KB
None

Describe (numeric):

,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,score,total_comments
count,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,1175.000000,1175.000000
mean,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,0.440715,16.062128
std,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,0.390111,14.780693
min,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,-1.000000,1.000000
25%,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,0.200000,7.000000
50%,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,0.468354,11.000000
75%,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,0.714286,21.000000
max,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,1.000000,112.000000

Null counts:
date               0
USD_KRW 종가         0
USD_KRW 시가         0
KOSPI 종가           0
KOSPI 거래량          0
KOSDAQ 종가          0
KOSDAQ 거래량         0
WTI Price          0
XAU Price          0
DJI 종가             0
DJI 거래량            0
SP500 종가           0
M1                 0
M2                 0
한국 정책금리            0
미국 정책금리            0
CPI                0
PPI                0
경상수지               0
score             11
total_comments    11
dtype: int64
========================================

In [95]:
df10["score"] = df10["score"].fillna(0)
df10["total_comments"] = df10["total_comments"].fillna(0)
scaler = StandardScaler()
df10['score'] = scaler.fit_transform(df10[['score']])
df10.rename(columns={"score": "comment_score_0.9"}, inplace=True)
df10.head()

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,...,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,comment_score_0.9,total_comments
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,...,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.666344,17.0
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,...,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-1.456628,53.0
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,...,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,0.094914,38.0
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,...,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.338810,23.0
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,...,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,-0.752439,14.0

In [97]:
output_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\modeling_data\comment_score_0.9_with_count.csv"
df10.to_csv(output_path, index=False)