In [17]:
import pandas as pd
import os

In [2]:
df_fx = pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\data\df_investing2.csv")

In [3]:
df_ksvkospi = pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\data\KSVKOSPI(KOSPI Volatility).csv")

In [4]:
df_261250 = pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\data\KODEX 미국달러선물레버리지(261250).csv")
df_261260 = pd.read_csv(r"C:\Users\james\J_Data_Lab\Project-FXCast\data\KODEX 미국달러선물인버스(261260).csv")

In [5]:
df_fx

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,6.445500e+08,70.99,2605.39,42573.73,383300000.0,5906.94,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,8.141300e+08,70.08,2620.00,42992.21,376960000.0,5970.84,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,8.292900e+08,69.53,2634.43,43325.80,270360000.0,6037.59,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,6.451000e+08,69.92,2613.20,43297.03,230410000.0,6040.04,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,6.577100e+08,69.34,2612.93,42906.95,449400000.0,5974.07,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,2020-01-08,1162.25,1168.30,2151.31,913830000.0,640.94,1.380000e+09,59.97,1555.81,28745.09,296430000.0,3253.10,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0
1182,2020-01-07,1167.30,1167.54,2175.54,568240000.0,663.44,9.703100e+08,64.92,1573.99,28583.68,266680000.0,3237.20,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0
1183,2020-01-06,1166.94,1165.89,2155.07,592670000.0,655.31,8.842800e+08,62.99,1565.96,28703.38,261810000.0,3246.30,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0
1184,2020-01-03,1164.95,1157.95,2176.46,631560000.0,669.93,9.038600e+08,63.10,1551.65,28634.88,239590000.0,3234.80,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0
1185,2020-01-02,1157.35,1155.02,2175.17,494680000.0,674.02,7.837300e+08,61.19,1528.94,28868.80,254290000.0,3257.80,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0

In [6]:
df_ksvkospi

                날짜     종가     시가     고가     저가    거래량    변동 %
0     2024- 12- 30  21.14  21.92  22.01  21.08  0.00K   1.25%
1     2024- 12- 27  20.88  20.80  22.10  20.57  0.00K   1.90%
2     2024- 12- 26  20.49  20.15  20.54  20.15  0.00K   2.35%
3     2024- 12- 24  20.02  19.81  20.39  19.80  0.00K  -0.25%
4     2024- 12- 23  20.07  20.96  21.03  19.95  0.00K  -6.43%
...            ...    ...    ...    ...    ...    ...     ...
1227  2020- 01- 08  15.97  16.30  17.07  15.57    NaN   5.90%
1228  2020- 01- 07  15.08  15.44  15.45  14.92    NaN  -5.04%
1229  2020- 01- 06  15.88  16.54  16.54  15.84    NaN   0.00%
1230  2020- 01- 03  15.88  15.34  16.18  15.17    NaN   3.12%
1231  2020- 01- 02  15.40  15.33  15.64  15.12    NaN   4.83%

[1232 rows x 7 columns]

In [7]:
df_261250

                날짜      종가      시가      고가      저가      거래량    변동 %
0     2024- 12- 30  17,195  17,160  17,210  17,005   61.92K   0.70%
1     2024- 12- 27  17,075  17,045  17,500  16,990  166.42K   0.53%
2     2024- 12- 26  16,985  16,840  16,985  16,800  155.82K   1.28%
3     2024- 12- 24  16,770  16,670  16,790  16,650   24.00K   0.60%
4     2024- 12- 23  16,670  16,525  16,670  16,520   32.33K   0.15%
...            ...     ...     ...     ...     ...      ...     ...
1054  2020- 03- 23  11,570  11,945  11,970  11,480    2.59M  -3.62%
1055  2020- 03- 19  12,005  11,390  12,500  11,270    4.12M   6.24%
1056  2020- 03- 18  11,300  11,120  11,300  10,960    1.56M   0.94%
1057  2020- 03- 17  11,195  11,085  11,225  10,990    1.44M   4.63%
1058  2020- 03- 13  10,700  10,785  10,915  10,655    2.82M   1.81%

[1059 rows x 7 columns]

In [8]:
df_261260

                날짜     종가     시가     고가     저가      거래량    변동 %
0     2024- 12- 30  5,050  5,065  5,110  5,045    4.16M  -0.59%
1     2024- 12- 27  5,080  5,110  5,110  4,960    1.80M  -0.88%
2     2024- 12- 26  5,125  5,165  5,175  5,115    2.17M  -1.06%
3     2024- 12- 24  5,180  5,220  5,220  5,175  606.36K  -0.77%
4     2024- 12- 23  5,220  5,245  5,260  5,215  457.49K   0.00%
...            ...    ...    ...    ...    ...      ...     ...
1245  2020- 01- 08  9,660  9,675  9,685  9,535   51.11K  -0.92%
1246  2020- 01- 07  9,750  9,715  9,785  9,715  120.70K   0.98%
1247  2020- 01- 06  9,655  9,710  9,740  9,645   40.52K  -0.87%
1248  2020- 01- 03  9,740  9,875  9,920  9,730   45.69K  -1.57%
1249  2020- 01- 02  9,895  9,960  9,965  9,880  137.13K  -0.20%

[1250 rows x 7 columns]

In [11]:
# 날짜 형식 통일
df_fx["date"] = pd.to_datetime(df_fx["date"])
df_ksvkospi["날짜"] = pd.to_datetime(df_ksvkospi["날짜"])
df_261250["날짜"] = pd.to_datetime(df_261250["날짜"])
df_261260["날짜"] = pd.to_datetime(df_261260["날짜"])

# 날짜 컬럼명 통일
df_ksvkospi = df_ksvkospi.rename(columns={"날짜": "date", "종가": "ksvkospi 종가"})
df_261250 = df_261250.rename(columns={"날짜": "date", "종가": "미국달러선물레버리지"})
df_261260 = df_261260.rename(columns={"날짜": "date", "종가": "미국달러선물인버스"})

# 컬럼명 변경
df_ksvkospi = df_ksvkospi.rename(columns={"종가": "ksvkospi 종가"})
df_261250 = df_261250.rename(columns={"종가": "미국달러선물레버리지"})
df_261260 = df_261260.rename(columns={"종가": "미국달러선물인버스"})

# 날짜 기준 병합
df_merged = df_fx.merge(df_ksvkospi[["date", "ksvkospi 종가"]], on="date", how="left")
df_merged = df_merged.merge(df_261250[["date", "미국달러선물레버리지"]], on="date", how="left")
df_merged = df_merged.merge(df_261260[["date", "미국달러선물인버스"]], on="date", how="left")

# 결과 확인
df_merged

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,...,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,ksvkospi 종가,미국달러선물레버리지,미국달러선물인버스
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,6.445500e+08,70.99,2605.39,42573.73,...,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0,21.14,"17,195","5,050"
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,8.141300e+08,70.08,2620.00,42992.21,...,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0,20.88,"17,075","5,080"
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,8.292900e+08,69.53,2634.43,43325.80,...,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0,20.49,"16,985","5,125"
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,6.451000e+08,69.92,2613.20,43297.03,...,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0,20.02,"16,770","5,180"
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,6.577100e+08,69.34,2612.93,42906.95,...,1274.2903,4183.5354,3.00,4.645161,1.9,119.52,12368.0,20.07,"16,670","5,220"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1181,2020-01-08,1162.25,1168.30,2151.31,913830000.0,640.94,1.380000e+09,59.97,1555.81,28745.09,...,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0,15.97,NaN,"9,660"
1182,2020-01-07,1167.30,1167.54,2175.54,568240000.0,663.44,9.703100e+08,64.92,1573.99,28583.68,...,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0,15.08,NaN,"9,750"
1183,2020-01-06,1166.94,1165.89,2155.07,592670000.0,655.31,8.842800e+08,62.99,1565.96,28703.38,...,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0,15.88,NaN,"9,655"
1184,2020-01-03,1164.95,1157.95,2176.46,631560000.0,669.93,9.038600e+08,63.10,1551.65,28634.88,...,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0,15.88,NaN,"9,740"
1185,2020-01-02,1157.35,1155.02,2175.17,494680000.0,674.02,7.837300e+08,61.19,1528.94,28868.80,...,944.3064,2935.6403,1.25,1.750000,1.2,101.02,185.0,15.40,NaN,"9,895"

In [12]:
def eda_basic_info(df, df_name="DataFrame"):
    print(f"\n===== {df_name} =====")
    print("Head (5 rows):")
    display(df.head())
    
    print("\nInfo:")
    print(df.info())
    
    print("\nDescribe (numeric):")
    display(df.describe())
    
    print("\nNull counts:")
    print(df.isnull().sum())
    
    print("="*40)

In [13]:
eda_basic_info(df_merged, "df")

===== df =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,...,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,ksvkospi 종가,미국달러선물레버리지,미국달러선물인버스
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,...,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,21.14,"17,195","5,050"
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,...,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,20.88,"17,075","5,080"
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,...,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,20.49,"16,985","5,125"
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,...,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,20.02,"16,770","5,180"
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,...,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,20.07,"16,670","5,220"

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         1186 non-null   datetime64[ns]
 1   USD_KRW 종가   1186 non-null   float64
 2   USD_KRW 시가   1186 non-null   float64
 3   KOSPI 종가     1186 non-null   float64
 4   KOSPI 거래량    1186 non-null   float64
 5   KOSDAQ 종가    1186 non-null   float64
 6   KOSDAQ 거래량   1186 non-null   float64
 7   WTI Price    1186 non-null   float64
 8   XAU Price    1186 non-null   float64
 9   DJI 종가       1186 non-null   float64
 10  DJI 거래량      1186 non-null   float64
 11  SP500 종가     1186 non-null   float64
 12  M1           1186 non-null   float64
 13  M2           1186 non-null   float64
 14  한국 정책금리      1186 non-null   float64
 15  미국 정책금리      1186 non-null   float64
 16  CPI          1186 non-null   float64
 17  PPI          1186 non-null   float64
 18  경상수지         1186 non-null   float64
 19  ksvkospi 종가  1186 non-null   float64
 20  미국달러선물레버리지   1014 non-null   object
 21  미국달러선물인버스    1186 non-null   object
dtypes: datetime64[ns](1), float64(19), object(2)
memory usage: 204.0+ KB
None

Describe (numeric):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,ksvkospi 종가
count,1186,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,1186.000000
mean,2022-06-25 11:34:30.151770624,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,20.305084
min,2020-01-02 00:00:00,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,11.730000
25%,2021-03-29 06:00:00,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,16.562500
50%,2022-06-25 12:00:00,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,18.380000
75%,2023-09-18 18:00:00,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,22.415000
max,2024-12-30 00:00:00,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,69.240000
std,NaN,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,6.604767

Null counts:
date             0
USD_KRW 종가       0
USD_KRW 시가       0
KOSPI 종가         0
KOSPI 거래량        0
KOSDAQ 종가        0
KOSDAQ 거래량       0
WTI Price        0
XAU Price        0
DJI 종가           0
DJI 거래량          0
SP500 종가         0
M1               0
M2               0
한국 정책금리          0
미국 정책금리          0
CPI              0
PPI              0
경상수지             0
ksvkospi 종가      0
미국달러선물레버리지     172
미국달러선물인버스        0
dtype: int64
========================================

In [14]:
# '미국달러선물레버리지' 컬럼 삭제
df_merged = df_merged.drop(columns=["미국달러선물레버리지"])

eda_basic_info(df_merged, "df")

===== df =====
Head (5 rows):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,...,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,ksvkospi 종가,미국달러선물인버스
0,2024-12-30,1469.25,1471.10,2399.49,303960000.0,678.19,644550000.0,70.99,2605.39,42573.73,...,5906.94,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,21.14,"5,050"
1,2024-12-27,1472.50,1468.40,2404.77,311290000.0,665.97,814130000.0,70.08,2620.00,42992.21,...,5970.84,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,20.88,"5,080"
2,2024-12-26,1467.08,1457.21,2429.67,322800000.0,675.64,829290000.0,69.53,2634.43,43325.80,...,6037.59,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,20.49,"5,125"
3,2024-12-24,1458.93,1453.28,2440.52,386780000.0,680.11,645100000.0,69.92,2613.20,43297.03,...,6040.04,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,20.02,"5,180"
4,2024-12-23,1451.28,1446.05,2442.01,428170000.0,679.24,657710000.0,69.34,2612.93,42906.95,...,5974.07,1274.2903,4183.5354,3.0,4.645161,1.9,119.52,12368.0,20.07,"5,220"

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         1186 non-null   datetime64[ns]
 1   USD_KRW 종가   1186 non-null   float64
 2   USD_KRW 시가   1186 non-null   float64
 3   KOSPI 종가     1186 non-null   float64
 4   KOSPI 거래량    1186 non-null   float64
 5   KOSDAQ 종가    1186 non-null   float64
 6   KOSDAQ 거래량   1186 non-null   float64
 7   WTI Price    1186 non-null   float64
 8   XAU Price    1186 non-null   float64
 9   DJI 종가       1186 non-null   float64
 10  DJI 거래량      1186 non-null   float64
 11  SP500 종가     1186 non-null   float64
 12  M1           1186 non-null   float64
 13  M2           1186 non-null   float64
 14  한국 정책금리      1186 non-null   float64
 15  미국 정책금리      1186 non-null   float64
 16  CPI          1186 non-null   float64
 17  PPI          1186 non-null   float64
 18  경상수지         1186 non-null   float64
 19  ksvkospi 종가  1186 non-null   float64
 20  미국달러선물인버스    1186 non-null   object
dtypes: datetime64[ns](1), float64(19), object(1)
memory usage: 194.7+ KB
None

Describe (numeric):

,date,USD_KRW 종가,USD_KRW 시가,KOSPI 종가,KOSPI 거래량,KOSDAQ 종가,KOSDAQ 거래량,WTI Price,XAU Price,DJI 종가,DJI 거래량,SP500 종가,M1,M2,한국 정책금리,미국 정책금리,CPI,PPI,경상수지,ksvkospi 종가
count,1186,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1.186000e+03,1186.000000,1186.000000,1186.000000,1186.000000,1186.00000,1186.000000,1186.000000,1186.000000,1186.000000
mean,2022-06-25 11:34:30.151770624,1256.282968,1256.633221,2596.073440,7.131867e+08,841.160118,1.306049e+09,69.533440,1937.514081,33603.138786,3.687432e+08,4250.179671,1219.394587,3616.388458,2.037789,2.60763,2.811298,111.501433,5333.790894,20.305084
min,2020-01-02 00:00:00,1083.530000,1083.870000,1457.640000,8.245100e+05,428.350000,6.196200e+08,7.790000,1471.000000,18591.930000,1.170400e+08,2237.400000,944.306400,2935.640300,0.500000,0.25000,-0.200000,98.930000,-4205.000000,11.730000
25%,2021-03-29 06:00:00,1181.822500,1182.460000,2399.310000,4.629025e+08,762.185000,9.524700e+08,62.090000,1778.307500,31022.087500,3.016050e+08,3810.150000,1184.088000,3309.121000,0.548387,0.25000,1.425000,103.890000,1862.000000,16.562500
50%,2022-06-25 12:00:00,1265.610000,1266.325000,2568.480000,6.137650e+08,847.505000,1.170000e+09,73.735000,1870.390000,33913.620000,3.433250e+08,4200.010000,1221.110000,3718.332800,1.750000,1.75000,2.700000,116.270000,6365.000000,18.380000
75%,2023-09-18 18:00:00,1333.020000,1333.395000,2758.637500,8.662025e+08,919.412500,1.500000e+09,82.030000,1985.455000,35627.822500,4.021650e+08,4591.015000,1287.187300,3843.786700,3.500000,5.25000,3.800000,117.500000,7438.000000,22.415000
max,2024-12-30 00:00:00,1472.500000,1471.100000,3305.210000,3.460000e+09,1060.000000,5.070000e+09,126.470000,2786.190000,45014.040000,1.220000e+09,6090.270000,1371.920900,4183.535400,3.500000,5.50000,6.300000,119.560000,13096.000000,69.240000
std,NaN,93.743223,93.787299,339.282251,3.554851e+08,114.428855,5.210409e+08,23.291945,263.590609,4657.788950,1.128756e+08,764.021938,103.680673,347.336672,1.303587,2.31595,1.658261,7.401748,4255.906435,6.604767

Null counts:
date           0
USD_KRW 종가     0
USD_KRW 시가     0
KOSPI 종가       0
KOSPI 거래량      0
KOSDAQ 종가      0
KOSDAQ 거래량     0
WTI Price      0
XAU Price      0
DJI 종가         0
DJI 거래량        0
SP500 종가       0
M1             0
M2             0
한국 정책금리        0
미국 정책금리        0
CPI            0
PPI            0
경상수지           0
ksvkospi 종가    0
미국달러선물인버스      0
dtype: int64
========================================

In [18]:
# csv 저장
data_path = r"C:\Users\james\J_Data_Lab\Project-FXCast\data"
df_merged.to_csv(os.path.join(data_path, "df_investing3.csv"), index=False, encoding="utf-8-sig")